#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/camellia

PRODUCT_COPY_FILES += \
    vendor/xiaomi/camellia/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/.tp/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.conf \
    vendor/xiaomi/camellia/proprietary/vendor/etc/.tp/thermal.off.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.off.conf \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/AudioParamOptions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_vext.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/CRSVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/CRSVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/CRSVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/CRSVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamTreeView.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamTreeView.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamTreeView.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/Ultrasound_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/Ultrasound_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamTreeView.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoWMicSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/AudioParamOptions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/AudioParamOptions.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/AudioParamOptions_vext.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/BtInfo_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/BtInfo_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/HpImpedance_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/HpImpedance_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/MicInfo_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/MicInfo_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/PlaybackACF_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/PlaybackACF_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/PlaybackDRC_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/PlaybackDRC_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/PlaybackHCF_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/PlaybackHCF_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/PlaybackVolAna_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/PlaybackVolDigi_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/PlaybackVolUI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/Playback_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/Playback_ParamTreeView.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/Playback_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/RecordDMNR_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/RecordDMNR_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/RecordFIR_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/RecordFIR_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/RecordUI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/RecordUI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/RecordVolUI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/RecordVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/RecordVol_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/RecordVol_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/Record_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/Record_ParamTreeView.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/Record_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/RingbackVolUI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/RingbackVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/RingbackVol_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/RingbackVol_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SoundEnhancement_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SoundEnhancement_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechDMNR_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechDMNR_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechEchoRef_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechGeneral_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechGeneral_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechMagiClarity_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechNetwork_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechNetwork_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechUI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechUI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechVolUI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechVol_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechVol_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/Speech_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/Speech_ParamTreeView.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/Speech_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/USBCall_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/USBCall_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/USBDevice_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/USBDevice_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/UplinkConfiguration_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPDMNR_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPDMNR_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPGeneral_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPGeneral_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPUI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPUI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPVolUI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPVol_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPVol_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIP_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIP_ParamTreeView.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIP_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPv2DMNR_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPv2General_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPv2General_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPv2UI_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPv2UI_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPv2_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPv2_ParamTreeView.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPv2_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoWDspAec_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoWDspAec_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoWEngineFeature_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoWEngineFeature_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoWEngineFeature_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoWHwVad_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoWHwVad_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoWVoiceCommand_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VolumeGainMapUL_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VolumeGainMap_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VolumeGainMap_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/Volume_AudioParam.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/audio_param_global/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/Volume_ParamUnitDesc.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/camera/CFR_para_Macro_i.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_Macro_i.bin \
    vendor/xiaomi/camellia/proprietary/vendor/etc/camera/CFR_para_Macro_ii.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_Macro_ii.bin \
    vendor/xiaomi/camellia/proprietary/vendor/etc/camera/CFR_para_Wide_H_i.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_Wide_H_i.bin \
    vendor/xiaomi/camellia/proprietary/vendor/etc/camera/CFR_para_Wide_H_ii.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_Wide_H_ii.bin \
    vendor/xiaomi/camellia/proprietary/vendor/etc/camera/CFR_para_Wide_i.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_Wide_i.bin \
    vendor/xiaomi/camellia/proprietary/vendor/etc/camera/CFR_para_Wide_ii.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_Wide_ii.bin \
    vendor/xiaomi/camellia/proprietary/vendor/etc/camera/golden_ov48b_i_gc02m1b_i.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/golden_ov48b_i_gc02m1b_i.bin \
    vendor/xiaomi/camellia/proprietary/vendor/etc/camera/golden_ov48b_ii_gc02m1b_ii.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/golden_ov48b_ii_gc02m1b_ii.bin \
    vendor/xiaomi/camellia/proprietary/vendor/etc/camera/mibokeh_mt6853_opencl.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mibokeh_mt6853_opencl.bin \
    vendor/xiaomi/camellia/proprietary/vendor/etc/camera/mibokeh_mt6853_parameter.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mibokeh_mt6853_parameter.bin \
    vendor/xiaomi/camellia/proprietary/vendor/etc/camera/sr_params.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sr_params.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/xiaomi/camellia/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/ecc_list_OP236.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP236.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Columbia.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Columbia.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Movistar_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Movistar_Peru.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/android.hardware.gnss-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-service.mediatek.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/android.hardware.keymaster@4.1-service.beanpod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.1-service.beanpod.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/android.hardware.media.c2@1.2-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.2-mediatek.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/chipinfo_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/chipinfo_init.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/init.bt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bt_drv.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/init.connfem.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.connfem.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/init.fmradio_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.fmradio_drv.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/init.gps_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_drv.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/init.thermal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/init.thermal_manager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal_manager.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/init.thermalloadalgod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermalloadalgod.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/init.vtservice_hidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vtservice_hidl.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/init.wlan_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wlan_drv.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/init.wmt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wmt_drv.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/lbs_hidl_service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/lbs_hidl_service.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/microtrust.bp_kmsetkey_ca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.bp_kmsetkey_ca.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/microtrust.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/tetheroffloadservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tetheroffloadservice.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/vpud.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vpud.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/xiaomi/camellia/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/xiaomi/camellia/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy \
    vendor/xiaomi/camellia/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy \
    vendor/xiaomi/camellia/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/xiaomi/camellia/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/st21nfc_conf.txt:$(TARGET_COPY_OUT_VENDOR)/etc/st21nfc_conf.txt \
    vendor/xiaomi/camellia/proprietary/vendor/etc/thermal-arvr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-arvr.conf \
    vendor/xiaomi/camellia/proprietary/vendor/etc/thermal-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-camera.conf \
    vendor/xiaomi/camellia/proprietary/vendor/etc/thermal-chg-only.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-chg-only.conf \
    vendor/xiaomi/camellia/proprietary/vendor/etc/thermal-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map.conf \
    vendor/xiaomi/camellia/proprietary/vendor/etc/thermal-mgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-mgame.conf \
    vendor/xiaomi/camellia/proprietary/vendor/etc/thermal-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-nolimits.conf \
    vendor/xiaomi/camellia/proprietary/vendor/etc/thermal-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-normal.conf \
    vendor/xiaomi/camellia/proprietary/vendor/etc/thermal-phone.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-phone.conf \
    vendor/xiaomi/camellia/proprietary/vendor/etc/thermal-tgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-tgame.conf \
    vendor/xiaomi/camellia/proprietary/vendor/etc/thermal-youtube.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-youtube.conf \
    vendor/xiaomi/camellia/proprietary/vendor/etc/thermald-devices.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermald-devices.conf \
    vendor/xiaomi/camellia/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/xiaomi/camellia/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_1_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_1_1.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/WMT_SOC.cfg \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/aw87559_pid_5a_fm_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87559_pid_5a_fm_0.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/aw87559_pid_5a_music_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87559_pid_5a_music_0.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/aw87559_pid_5a_off_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87559_pid_5a_off_0.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/aw87559_pid_5a_rcv_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87559_pid_5a_rcv_0.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/aw87559_pid_5a_voice_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87559_pid_5a_voice_0.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/aw87xxx_vmax_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87xxx_vmax_0.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/awinic_params.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/awinic_params.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/fm_cust.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/fm_cust.cfg \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/focaltech_mp_fw_tianma.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_mp_fw_tianma.ini \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/focaltech_ts_fw_tianma.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_ts_fw_tianma.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/fs1815.fsm:$(TARGET_COPY_OUT_VENDOR)/firmware/fs1815.fsm \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/mt6631_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_coeff.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/mt6631_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_patch.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/nt36672c_tm_01_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36672c_tm_01_ts_fw.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/nt36672c_tm_01_ts_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36672c_tm_01_ts_mp.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/nt36672c_tr_02_kn_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36672c_tr_02_kn_ts_fw.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/nt36672c_tr_02_kn_ts_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36672c_tr_02_kn_ts_mp.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/nt36672c_tr_02_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36672c_tr_02_ts_fw.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/nt36672c_tr_02_ts_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36672c_tr_02_ts_mp.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/nt36672d_tm_03_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36672d_tm_03_ts_fw.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/nt36672d_tm_03_ts_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36672d_tm_03_ts_mp.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/soc2_2_ram_bt_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_1_1_hdr.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/soc2_2_ram_mcu_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_1_1_hdr.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/soc2_2_ram_wifi_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_1_1_hdr.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/st21nfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/st21nfc_fw.bin \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/txpowerctrl.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/txpowerctrl.cfg \
    vendor/xiaomi/camellia/proprietary/vendor/firmware/wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi.cfg \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/020f0000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/020f0000000000000000000000000000.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/05120000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/05120000000000000000000000000000.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/06090000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/06090000000000000000000000000000.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/08010203000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08010203000000000000000000000000.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/08030000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08030000000000000000000000000000.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/08040000000000000000000000003419.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08040000000000000000000000003419.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/08050000000000000000000000003419.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08050000000000000000000000003419.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/08110000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08110000000000000000000000000000.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/14498ace2a8f11e880c8509a4c146f4c.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/14498ace2a8f11e880c8509a4c146f4c.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/3d08821c33a611e6a1fa089e01c83aa2.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/3d08821c33a611e6a1fa089e01c83aa2.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/40188311faf343488db888ad39496f9a.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/40188311faf343488db888ad39496f9a.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/5020170115e016302017012521300000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/5020170115e016302017012521300000.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/655a4b46cd7711eaaafbf382a6988e7b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/655a4b46cd7711eaaafbf382a6988e7b.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/7778c03fc30c4dd0a319ea29643d4d4b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/7778c03fc30c4dd0a319ea29643d4d4b.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/86f623f6a2994dfdb560ffd3e5a62c29.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/86f623f6a2994dfdb560ffd3e5a62c29.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/8888c03fc30c4dd0a319ea29643d4d4b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/8888c03fc30c4dd0a319ea29643d4d4b.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/93feffccd8ca11e796c7c7a21acb4932.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/93feffccd8ca11e796c7c7a21acb4932.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/a985d3eb3b524d44be6c628a813561e8.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/a985d3eb3b524d44be6c628a813561e8.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/c09c9c5daa504b78b0e46eda61556c3a.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/c09c9c5daa504b78b0e46eda61556c3a.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/c1882f2d885e4e13a8c8e2622461b2fa.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/c1882f2d885e4e13a8c8e2622461b2fa.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/d78d338b1ac349e09f65f4efe179739d.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/d78d338b1ac349e09f65f4efe179739d.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/e5140b3376fa4c63ab18062caab2fb5c.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/e5140b3376fa4c63ab18062caab2fb5c.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/e97c270ea5c44c58bcd3384a2fa2539e.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/e97c270ea5c44c58bcd3384a2fa2539e.ta \
    vendor/xiaomi/camellia/proprietary/vendor/thh/ta/isee_model.json:$(TARGET_COPY_OUT_VENDOR)/thh/ta/isee_model.json

PRODUCT_PACKAGES += \
    libaedv \
    libbwc \
    libfile_op \
    libgz_uree \
    libion_mtk \
    libion_ulit \
    libladder \
    libmtkcutils \
    libmtkproperty \
    libmtkrillog \
    libnvram \
    libnvram_sec \
    libmtk_drvb \
    AVCSecureVdecCA \
    HEVCSecureVdecCA \
    VP9SecureVdecCA \
    audio.primary.mt6833 \
    audio.r_submix.mt6833 \
    awinic.audio.effect \
    sound_trigger.primary.default \
    libMtkSpeechEnh \
    lib_iir \
    lib_speech_enh \
    libalsautils-v31 \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libcvsd_mtk \
    libfgauge_gm30 \
    libgz_gp_client \
    libmsbc_mtk \
    libmtcloader \
    libmtklimiter_vendor \
    libmtkshifter_vendor \
    libnxp_extamp_intf \
    librt_extamp_intf \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libthermalalgo \
    libvcodec_oal \
    libvcodec_utility \
    libvcodecdrv \
    libvcodecdrv_header_stub \
    libvow_ap_test_aa \
    libvow_ap_test_dd \
    libvow_ap_test_ha \
    libvow_ap_test_hh \
    libvow_ap_test_nn \
    libvpu5 \
    libvpud_vcodec \
    vendor.mediatek.hardware.audio@7.1 \
    arm.graphics-V1-ndk_platform \
    libGLES_mali \
    libGLES_meow \
    libMEOW_data \
    libMEOW_gift \
    libMEOW_qt \
    libMEOW_trace \
    gc02m1b_aac_depth_mipi_mono_IdxMgr \
    gc02m1b_aac_depth_mipi_mono_tuning \
    gc02m1b_qtech_depth_mipi_mono_IdxMgr \
    gc02m1b_qtech_depth_mipi_mono_india_tuning \
    gc02m1b_qtech_depth_mipi_mono_tuning \
    hi259h_aac_macro_mipi_raw_IdxMgr \
    hi259h_aac_macro_mipi_raw_tuning \
    hi259h_qtech_macro_mipi_raw_IdxMgr \
    hi259h_qtech_macro_mipi_raw_india_tuning \
    hi259h_qtech_macro_mipi_raw_tuning \
    hq_asd \
    android.hardware.camera.provider@2.6-impl-mediatek \
    android.hardware.gnss-impl-mediatek \
    android.hardware.gnss@2.1-impl-mediatek \
    android.hardware.graphics.allocator@4.0-impl-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    consumerir.common \
    fingerprint.fpc.default \
    gatekeeper.beanpod \
    gf_fingerprint.goodix.default \
    gps.default \
    hwcomposer.mt6833 \
    sensors.mt6833 \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    vendor.mediatek.hardware.camera.ccap@1.0-impl \
    vendor.mediatek.hardware.camera.isphal@1.0-impl \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    vendor.mediatek.hardware.mms@1.6-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    vendor.mediatek.hardware.pq@2.13-impl \
    vendor.mediatek.hardware.videotelephony@1.0-impl \
    vulkan.mali \
    lbs_hidl_service-impl \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.ae.stat \
    lib3a.af.assist \
    lib3a.af.assist.utils \
    lib3a.af.core \
    lib3a.af \
    lib3a.alsflicker \
    lib3a.awb.core \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.custom.ae \
    lib3a.dce \
    lib3a.flash \
    lib3a.flicker \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    lib3a.sensors.color \
    lib3a.sensors.flicker \
    libCamera_gc02m1baacdepthmipimono_E2EHDR_Preview \
    libCamera_gc02m1baacdepthmipimono_E2EHDR_Video \
    libCamera_gc02m1baacdepthmipimono_Face_Capture \
    libCamera_gc02m1baacdepthmipimono_Flash_Capture \
    libCamera_gc02m1baacdepthmipimono_HDR_Capture \
    libCamera_gc02m1baacdepthmipimono_HDR_Preview \
    libCamera_gc02m1baacdepthmipimono_HDR_Video \
    libCamera_gc02m1baacdepthmipimono_N3D_Capture \
    libCamera_gc02m1baacdepthmipimono_N3D_Preview \
    libCamera_gc02m1baacdepthmipimono_N3D_Video \
    libCamera_gc02m1baacdepthmipimono_P1_YUV \
    libCamera_gc02m1baacdepthmipimono_Scene_Capture \
    libCamera_gc02m1baacdepthmipimono_Scene_Capture_4cell \
    libCamera_gc02m1baacdepthmipimono_Scene_Preview \
    libCamera_gc02m1baacdepthmipimono_Scene_Preview_4k \
    libCamera_gc02m1baacdepthmipimono_Scene_Preview_ZSD_Flash \
    libCamera_gc02m1baacdepthmipimono_Video_1080 \
    libCamera_gc02m1baacdepthmipimono_Video_4k \
    libCamera_gc02m1bqtechdepthmipimono_E2EHDR_Preview \
    libCamera_gc02m1bqtechdepthmipimono_E2EHDR_Video \
    libCamera_gc02m1bqtechdepthmipimono_Face_Capture \
    libCamera_gc02m1bqtechdepthmipimono_Flash_Capture \
    libCamera_gc02m1bqtechdepthmipimono_HDR_Capture \
    libCamera_gc02m1bqtechdepthmipimono_HDR_Preview \
    libCamera_gc02m1bqtechdepthmipimono_HDR_Video \
    libCamera_gc02m1bqtechdepthmipimono_N3D_Capture \
    libCamera_gc02m1bqtechdepthmipimono_N3D_Preview \
    libCamera_gc02m1bqtechdepthmipimono_N3D_Video \
    libCamera_gc02m1bqtechdepthmipimono_P1_YUV \
    libCamera_gc02m1bqtechdepthmipimono_Scene_Capture \
    libCamera_gc02m1bqtechdepthmipimono_Scene_Capture_4cell \
    libCamera_gc02m1bqtechdepthmipimono_Scene_Preview \
    libCamera_gc02m1bqtechdepthmipimono_Scene_Preview_4k \
    libCamera_gc02m1bqtechdepthmipimono_Scene_Preview_ZSD_Flash \
    libCamera_gc02m1bqtechdepthmipimono_Video_1080 \
    libCamera_gc02m1bqtechdepthmipimono_Video_4k \
    libCamera_gc02m1bqtechdepthmipimonoindia_E2EHDR_Preview \
    libCamera_gc02m1bqtechdepthmipimonoindia_E2EHDR_Video \
    libCamera_gc02m1bqtechdepthmipimonoindia_Face_Capture \
    libCamera_gc02m1bqtechdepthmipimonoindia_Flash_Capture \
    libCamera_gc02m1bqtechdepthmipimonoindia_HDR_Capture \
    libCamera_gc02m1bqtechdepthmipimonoindia_HDR_Preview \
    libCamera_gc02m1bqtechdepthmipimonoindia_HDR_Video \
    libCamera_gc02m1bqtechdepthmipimonoindia_N3D_Capture \
    libCamera_gc02m1bqtechdepthmipimonoindia_N3D_Preview \
    libCamera_gc02m1bqtechdepthmipimonoindia_N3D_Video \
    libCamera_gc02m1bqtechdepthmipimonoindia_P1_YUV \
    libCamera_gc02m1bqtechdepthmipimonoindia_Scene_Capture \
    libCamera_gc02m1bqtechdepthmipimonoindia_Scene_Capture_4cell \
    libCamera_gc02m1bqtechdepthmipimonoindia_Scene_Preview \
    libCamera_gc02m1bqtechdepthmipimonoindia_Scene_Preview_4k \
    libCamera_gc02m1bqtechdepthmipimonoindia_Scene_Preview_ZSD_Flash \
    libCamera_gc02m1bqtechdepthmipimonoindia_Video_1080 \
    libCamera_gc02m1bqtechdepthmipimonoindia_Video_4k \
    libCamera_hi259haacmacromipiraw_E2EHDR_Preview \
    libCamera_hi259haacmacromipiraw_E2EHDR_Video \
    libCamera_hi259haacmacromipiraw_Face_Capture \
    libCamera_hi259haacmacromipiraw_Flash_Capture \
    libCamera_hi259haacmacromipiraw_Flash_Preview \
    libCamera_hi259haacmacromipiraw_HDR_Capture \
    libCamera_hi259haacmacromipiraw_HDR_Preview \
    libCamera_hi259haacmacromipiraw_HDR_Video \
    libCamera_hi259haacmacromipiraw_MIBeautyFace_Capture \
    libCamera_hi259haacmacromipiraw_MIBeautyFace_Preview \
    libCamera_hi259haacmacromipiraw_N3D_Capture \
    libCamera_hi259haacmacromipiraw_N3D_Preview \
    libCamera_hi259haacmacromipiraw_N3D_Video \
    libCamera_hi259haacmacromipiraw_P1_YUV \
    libCamera_hi259haacmacromipiraw_ProColorCapture \
    libCamera_hi259haacmacromipiraw_Scene_Capture \
    libCamera_hi259haacmacromipiraw_Scene_Capture_4cell \
    libCamera_hi259haacmacromipiraw_Scene_Preview \
    libCamera_hi259haacmacromipiraw_Scene_Preview_4k \
    libCamera_hi259haacmacromipiraw_Scene_Preview_ZSD_Flash \
    libCamera_hi259haacmacromipiraw_Video_1080 \
    libCamera_hi259haacmacromipiraw_Video_4k \
    libCamera_hi259haacmacromipiraw_Zoom_Capture \
    libCamera_hi259haacmacromipiraw_Zoom_Preview \
    libCamera_hi259hqtechmacromipiraw_E2EHDR_Preview \
    libCamera_hi259hqtechmacromipiraw_E2EHDR_Video \
    libCamera_hi259hqtechmacromipiraw_Face_Capture \
    libCamera_hi259hqtechmacromipiraw_Flash_Capture \
    libCamera_hi259hqtechmacromipiraw_Flash_Preview \
    libCamera_hi259hqtechmacromipiraw_HDR_Capture \
    libCamera_hi259hqtechmacromipiraw_HDR_Preview \
    libCamera_hi259hqtechmacromipiraw_HDR_Video \
    libCamera_hi259hqtechmacromipiraw_MIBeautyFace_Capture \
    libCamera_hi259hqtechmacromipiraw_MIBeautyFace_Preview \
    libCamera_hi259hqtechmacromipiraw_N3D_Capture \
    libCamera_hi259hqtechmacromipiraw_N3D_Preview \
    libCamera_hi259hqtechmacromipiraw_N3D_Video \
    libCamera_hi259hqtechmacromipiraw_P1_YUV \
    libCamera_hi259hqtechmacromipiraw_ProColorCapture \
    libCamera_hi259hqtechmacromipiraw_ProColorPreview \
    libCamera_hi259hqtechmacromipiraw_Scene_Capture \
    libCamera_hi259hqtechmacromipiraw_Scene_Capture_4cell \
    libCamera_hi259hqtechmacromipiraw_Scene_Preview \
    libCamera_hi259hqtechmacromipiraw_Scene_Preview_4k \
    libCamera_hi259hqtechmacromipiraw_Scene_Preview_ZSD_Flash \
    libCamera_hi259hqtechmacromipiraw_Video_1080 \
    libCamera_hi259hqtechmacromipiraw_Video_4k \
    libCamera_hi259hqtechmacromipiraw_Zoom_Capture \
    libCamera_hi259hqtechmacromipiraw_Zoom_Preview \
    libCamera_hi259hqtechmacromipirawindia_E2EHDR_Preview \
    libCamera_hi259hqtechmacromipirawindia_E2EHDR_Video \
    libCamera_hi259hqtechmacromipirawindia_Face_Capture \
    libCamera_hi259hqtechmacromipirawindia_Flash_Capture \
    libCamera_hi259hqtechmacromipirawindia_Flash_Preview \
    libCamera_hi259hqtechmacromipirawindia_HDR_Capture \
    libCamera_hi259hqtechmacromipirawindia_HDR_Preview \
    libCamera_hi259hqtechmacromipirawindia_HDR_Video \
    libCamera_hi259hqtechmacromipirawindia_MIBeautyFace_Capture \
    libCamera_hi259hqtechmacromipirawindia_MIBeautyFace_Preview \
    libCamera_hi259hqtechmacromipirawindia_N3D_Capture \
    libCamera_hi259hqtechmacromipirawindia_N3D_Preview \
    libCamera_hi259hqtechmacromipirawindia_N3D_Video \
    libCamera_hi259hqtechmacromipirawindia_P1_YUV \
    libCamera_hi259hqtechmacromipirawindia_ProColorCapture \
    libCamera_hi259hqtechmacromipirawindia_ProColorPreview \
    libCamera_hi259hqtechmacromipirawindia_Scene_Capture \
    libCamera_hi259hqtechmacromipirawindia_Scene_Capture_4cell \
    libCamera_hi259hqtechmacromipirawindia_Scene_Preview \
    libCamera_hi259hqtechmacromipirawindia_Scene_Preview_4k \
    libCamera_hi259hqtechmacromipirawindia_Scene_Preview_ZSD_Flash \
    libCamera_hi259hqtechmacromipirawindia_Video_1080 \
    libCamera_hi259hqtechmacromipirawindia_Video_4k \
    libCamera_hi259hqtechmacromipirawindia_Zoom_Capture \
    libCamera_hi259hqtechmacromipirawindia_Zoom_Preview \
    libCamera_ov02b10aacmacromipiraw_E2EHDR_Preview \
    libCamera_ov02b10aacmacromipiraw_E2EHDR_Video \
    libCamera_ov02b10aacmacromipiraw_Face_Capture \
    libCamera_ov02b10aacmacromipiraw_Flash_Capture \
    libCamera_ov02b10aacmacromipiraw_HDR_Capture \
    libCamera_ov02b10aacmacromipiraw_HDR_Preview \
    libCamera_ov02b10aacmacromipiraw_HDR_Video \
    libCamera_ov02b10aacmacromipiraw_MIBeautyFace_Capture \
    libCamera_ov02b10aacmacromipiraw_MIBeautyFace_Preview \
    libCamera_ov02b10aacmacromipiraw_N3D_Capture \
    libCamera_ov02b10aacmacromipiraw_N3D_Preview \
    libCamera_ov02b10aacmacromipiraw_N3D_Video \
    libCamera_ov02b10aacmacromipiraw_P1_YUV \
    libCamera_ov02b10aacmacromipiraw_Scene_Capture \
    libCamera_ov02b10aacmacromipiraw_Scene_Capture_4cell \
    libCamera_ov02b10aacmacromipiraw_Scene_Preview \
    libCamera_ov02b10aacmacromipiraw_Scene_Preview_4k \
    libCamera_ov02b10aacmacromipiraw_Scene_Preview_ZSD_Flash \
    libCamera_ov02b10aacmacromipiraw_Video_1080 \
    libCamera_ov02b10aacmacromipiraw_Video_4k \
    libCamera_ov02b10aacmacromipiraw_Zoom_Capture \
    libCamera_ov02b10aacmacromipiraw_Zoom_Preview \
    libCamera_ov48baacmainmipiraw_3rd_Party_camera_00 \
    libCamera_ov48baacmainmipiraw_3rd_Party_camera_01 \
    libCamera_ov48baacmainmipiraw_3rd_Party_camera_Capture \
    libCamera_ov48baacmainmipiraw_Default_Capture_XTS \
    libCamera_ov48baacmainmipiraw_Default_Preview \
    libCamera_ov48baacmainmipiraw_EIS_Video_1080 \
    libCamera_ov48baacmainmipiraw_EIS_Video_1080_ZOOM \
    libCamera_ov48baacmainmipiraw_EIS_Video_720 \
    libCamera_ov48baacmainmipiraw_EIS_Video_720_ZOOM \
    libCamera_ov48baacmainmipiraw_Face_Capture \
    libCamera_ov48baacmainmipiraw_Flash_Capture \
    libCamera_ov48baacmainmipiraw_Flash_Preview \
    libCamera_ov48baacmainmipiraw_MICamera_Panorama \
    libCamera_ov48baacmainmipiraw_MI_48M_Capture \
    libCamera_ov48baacmainmipiraw_MI_48M_Flash_Capture \
    libCamera_ov48baacmainmipiraw_MI_Bokeh_Capture \
    libCamera_ov48baacmainmipiraw_MI_Bokeh_Capture_Screen \
    libCamera_ov48baacmainmipiraw_MI_HDR_Capture \
    libCamera_ov48baacmainmipiraw_MI_Night_Capture \
    libCamera_ov48baacmainmipiraw_MI_Night_Capture_10x \
    libCamera_ov48baacmainmipiraw_MI_Night_Capture_6x \
    libCamera_ov48baacmainmipiraw_MI_Prefessional_Capture \
    libCamera_ov48baacmainmipiraw_MI_Prefessional_Capture_10x \
    libCamera_ov48baacmainmipiraw_MI_Prefessional_Capture_6x \
    libCamera_ov48baacmainmipiraw_MI_SlowVideo \
    libCamera_ov48baacmainmipiraw_MI_Zoom_Capture_10x \
    libCamera_ov48baacmainmipiraw_MI_Zoom_Preview_10x \
    libCamera_ov48baacmainmipiraw_MI_Zoom_Preview_6x \
    libCamera_ov48baacmainmipiraw_ProColorCapture \
    libCamera_ov48baacmainmipiraw_QQ_Call \
    libCamera_ov48baacmainmipiraw_QQ_Capture \
    libCamera_ov48baacmainmipiraw_Scene_Capture \
    libCamera_ov48baacmainmipiraw_Scene_Capture_4cell \
    libCamera_ov48baacmainmipiraw_Scene_Preview \
    libCamera_ov48baacmainmipiraw_TTPIC_Capture \
    libCamera_ov48baacmainmipiraw_Video_1080 \
    libCamera_ov48baacmainmipiraw_Video_1080_ZOOM \
    libCamera_ov48baacmainmipiraw_Video_720 \
    libCamera_ov48baacmainmipiraw_Video_720_ZOOM \
    libCamera_ov48baacmainmipiraw_Video_other \
    libCamera_ov48baacmainmipiraw_Wechat_Call \
    libCamera_ov48baacmainmipiraw_Wechat_Capture \
    libCamera_ov48bqtechmainmipiraw_3rd_Party_camera_00 \
    libCamera_ov48bqtechmainmipiraw_3rd_Party_camera_01 \
    libCamera_ov48bqtechmainmipiraw_3rd_Party_camera_Capture \
    libCamera_ov48bqtechmainmipiraw_Default_Capture_XTS \
    libCamera_ov48bqtechmainmipiraw_EIS_Video_1080 \
    libCamera_ov48bqtechmainmipiraw_EIS_Video_1080_ZOOM \
    libCamera_ov48bqtechmainmipiraw_EIS_Video_720 \
    libCamera_ov48bqtechmainmipiraw_EIS_Video_720_ZOOM \
    libCamera_ov48bqtechmainmipiraw_Face_Capture \
    libCamera_ov48bqtechmainmipiraw_Flash_Capture \
    libCamera_ov48bqtechmainmipiraw_Flash_Preview \
    libCamera_ov48bqtechmainmipiraw_MICamera_Panorama \
    libCamera_ov48bqtechmainmipiraw_MI_48M_Capture \
    libCamera_ov48bqtechmainmipiraw_MI_48M_Flash_Capture \
    libCamera_ov48bqtechmainmipiraw_MI_Bokeh_Capture \
    libCamera_ov48bqtechmainmipiraw_MI_Bokeh_Capture_Screen \
    libCamera_ov48bqtechmainmipiraw_MI_HDR_Capture \
    libCamera_ov48bqtechmainmipiraw_MI_Night_Capture \
    libCamera_ov48bqtechmainmipiraw_MI_Night_Capture_10x \
    libCamera_ov48bqtechmainmipiraw_MI_Night_Capture_6x \
    libCamera_ov48bqtechmainmipiraw_MI_Prefessional_Capture \
    libCamera_ov48bqtechmainmipiraw_MI_Prefessional_Capture_10x \
    libCamera_ov48bqtechmainmipiraw_MI_Prefessional_Capture_6x \
    libCamera_ov48bqtechmainmipiraw_MI_SlowVideo \
    libCamera_ov48bqtechmainmipiraw_MI_Zoom_Capture_10x \
    libCamera_ov48bqtechmainmipiraw_MI_Zoom_Preview_10x \
    libCamera_ov48bqtechmainmipiraw_MI_Zoom_Preview_6x \
    libCamera_ov48bqtechmainmipiraw_ProColorCapture \
    libCamera_ov48bqtechmainmipiraw_ProColorPreview \
    libCamera_ov48bqtechmainmipiraw_QQ_Call \
    libCamera_ov48bqtechmainmipiraw_QQ_Capture \
    libCamera_ov48bqtechmainmipiraw_Scene_Capture \
    libCamera_ov48bqtechmainmipiraw_Scene_Capture_4cell \
    libCamera_ov48bqtechmainmipiraw_Scene_Preview \
    libCamera_ov48bqtechmainmipiraw_TTPIC_Capture \
    libCamera_ov48bqtechmainmipiraw_Video_1080 \
    libCamera_ov48bqtechmainmipiraw_Video_1080_ZOOM \
    libCamera_ov48bqtechmainmipiraw_Video_720 \
    libCamera_ov48bqtechmainmipiraw_Video_720_ZOOM \
    libCamera_ov48bqtechmainmipiraw_Video_other \
    libCamera_ov48bqtechmainmipiraw_Wechat_Call \
    libCamera_ov48bqtechmainmipiraw_Wechat_Capture \
    libCamera_ov48bqtechmainmipirawindia_3rd_Party_camera_00 \
    libCamera_ov48bqtechmainmipirawindia_3rd_Party_camera_01 \
    libCamera_ov48bqtechmainmipirawindia_3rd_Party_camera_Capture \
    libCamera_ov48bqtechmainmipirawindia_Default_Capture_XTS \
    libCamera_ov48bqtechmainmipirawindia_EIS_Video_1080 \
    libCamera_ov48bqtechmainmipirawindia_EIS_Video_1080_ZOOM \
    libCamera_ov48bqtechmainmipirawindia_EIS_Video_720 \
    libCamera_ov48bqtechmainmipirawindia_EIS_Video_720_ZOOM \
    libCamera_ov48bqtechmainmipirawindia_Face_Capture \
    libCamera_ov48bqtechmainmipirawindia_Flash_Capture \
    libCamera_ov48bqtechmainmipirawindia_Flash_Preview \
    libCamera_ov48bqtechmainmipirawindia_MICamera_Panorama \
    libCamera_ov48bqtechmainmipirawindia_MI_48M_Capture \
    libCamera_ov48bqtechmainmipirawindia_MI_48M_Flash_Capture \
    libCamera_ov48bqtechmainmipirawindia_MI_Bokeh_Capture \
    libCamera_ov48bqtechmainmipirawindia_MI_Bokeh_Capture_Screen \
    libCamera_ov48bqtechmainmipirawindia_MI_HDR_Capture \
    libCamera_ov48bqtechmainmipirawindia_MI_Night_Capture \
    libCamera_ov48bqtechmainmipirawindia_MI_Night_Capture_10x \
    libCamera_ov48bqtechmainmipirawindia_MI_Night_Capture_6x \
    libCamera_ov48bqtechmainmipirawindia_MI_Prefessional_Capture \
    libCamera_ov48bqtechmainmipirawindia_MI_Prefessional_Capture_10x \
    libCamera_ov48bqtechmainmipirawindia_MI_Prefessional_Capture_6x \
    libCamera_ov48bqtechmainmipirawindia_MI_SlowVideo \
    libCamera_ov48bqtechmainmipirawindia_MI_Zoom_Capture_10x \
    libCamera_ov48bqtechmainmipirawindia_MI_Zoom_Preview_10x \
    libCamera_ov48bqtechmainmipirawindia_MI_Zoom_Preview_6x \
    libCamera_ov48bqtechmainmipirawindia_ProColorCapture \
    libCamera_ov48bqtechmainmipirawindia_ProColorPreview \
    libCamera_ov48bqtechmainmipirawindia_QQ_Call \
    libCamera_ov48bqtechmainmipirawindia_QQ_Capture \
    libCamera_ov48bqtechmainmipirawindia_Scene_Capture \
    libCamera_ov48bqtechmainmipirawindia_Scene_Capture_4cell \
    libCamera_ov48bqtechmainmipirawindia_Scene_Preview \
    libCamera_ov48bqtechmainmipirawindia_TTPIC_Capture \
    libCamera_ov48bqtechmainmipirawindia_Video_1080 \
    libCamera_ov48bqtechmainmipirawindia_Video_1080_ZOOM \
    libCamera_ov48bqtechmainmipirawindia_Video_720 \
    libCamera_ov48bqtechmainmipirawindia_Video_720_ZOOM \
    libCamera_ov48bqtechmainmipirawindia_Video_other \
    libCamera_ov48bqtechmainmipirawindia_Wechat_Call \
    libCamera_ov48bqtechmainmipirawindia_Wechat_Capture \
    libCamera_ov8856aacfrontmipiraw_3rd_Party_camera_00 \
    libCamera_ov8856aacfrontmipiraw_3rd_Party_camera_01 \
    libCamera_ov8856aacfrontmipiraw_3rd_Party_camera_Capture \
    libCamera_ov8856aacfrontmipiraw_Default_Capture_XTS \
    libCamera_ov8856aacfrontmipiraw_EIS_Video_1080 \
    libCamera_ov8856aacfrontmipiraw_EIS_Video_720 \
    libCamera_ov8856aacfrontmipiraw_Face_Capture \
    libCamera_ov8856aacfrontmipiraw_MICamera_Panorama \
    libCamera_ov8856aacfrontmipiraw_MI_Bokeh_Capture \
    libCamera_ov8856aacfrontmipiraw_MI_HDR_Capture \
    libCamera_ov8856aacfrontmipiraw_QQ_Call \
    libCamera_ov8856aacfrontmipiraw_QQ_Capture \
    libCamera_ov8856aacfrontmipiraw_Scene_Capture \
    libCamera_ov8856aacfrontmipiraw_Scene_Capture_4cell \
    libCamera_ov8856aacfrontmipiraw_Scene_Preview \
    libCamera_ov8856aacfrontmipiraw_TTPIC_Capture \
    libCamera_ov8856aacfrontmipiraw_Video_1080 \
    libCamera_ov8856aacfrontmipiraw_Video_720 \
    libCamera_ov8856aacfrontmipiraw_Video_other \
    libCamera_ov8856aacfrontmipiraw_Wechat_Call \
    libCamera_ov8856aacfrontmipiraw_Wechat_Capture \
    libCamera_ov8856ofilmfrontmipiraw_3rd_Party_camera_00 \
    libCamera_ov8856ofilmfrontmipiraw_3rd_Party_camera_01 \
    libCamera_ov8856ofilmfrontmipiraw_3rd_Party_camera_Capture \
    libCamera_ov8856ofilmfrontmipiraw_Default_Capture_XTS \
    libCamera_ov8856ofilmfrontmipiraw_EIS_Video_1080 \
    libCamera_ov8856ofilmfrontmipiraw_EIS_Video_720 \
    libCamera_ov8856ofilmfrontmipiraw_Face_Capture \
    libCamera_ov8856ofilmfrontmipiraw_MICamera_Panorama \
    libCamera_ov8856ofilmfrontmipiraw_MI_Bokeh_Capture \
    libCamera_ov8856ofilmfrontmipiraw_MI_HDR_Capture \
    libCamera_ov8856ofilmfrontmipiraw_QQ_Call \
    libCamera_ov8856ofilmfrontmipiraw_QQ_Capture \
    libCamera_ov8856ofilmfrontmipiraw_Scene_Capture \
    libCamera_ov8856ofilmfrontmipiraw_Scene_Capture_4cell \
    libCamera_ov8856ofilmfrontmipiraw_Scene_Preview \
    libCamera_ov8856ofilmfrontmipiraw_TTPIC_Capture \
    libCamera_ov8856ofilmfrontmipiraw_Video_1080 \
    libCamera_ov8856ofilmfrontmipiraw_Video_720 \
    libCamera_ov8856ofilmfrontmipiraw_Video_other \
    libCamera_ov8856ofilmfrontmipiraw_Wechat_Call \
    libCamera_ov8856ofilmfrontmipiraw_Wechat_Capture \
    libCamera_ov8856ofilmfrontmipirawindia_3rd_Party_camera_00 \
    libCamera_ov8856ofilmfrontmipirawindia_3rd_Party_camera_01 \
    libCamera_ov8856ofilmfrontmipirawindia_3rd_Party_camera_Capture \
    libCamera_ov8856ofilmfrontmipirawindia_Default_Capture_XTS \
    libCamera_ov8856ofilmfrontmipirawindia_EIS_Video_1080 \
    libCamera_ov8856ofilmfrontmipirawindia_EIS_Video_720 \
    libCamera_ov8856ofilmfrontmipirawindia_Face_Capture \
    libCamera_ov8856ofilmfrontmipirawindia_MICamera_Panorama \
    libCamera_ov8856ofilmfrontmipirawindia_MI_Bokeh_Capture \
    libCamera_ov8856ofilmfrontmipirawindia_MI_HDR_Capture \
    libCamera_ov8856ofilmfrontmipirawindia_QQ_Call \
    libCamera_ov8856ofilmfrontmipirawindia_QQ_Capture \
    libCamera_ov8856ofilmfrontmipirawindia_Scene_Capture \
    libCamera_ov8856ofilmfrontmipirawindia_Scene_Capture_4cell \
    libCamera_ov8856ofilmfrontmipirawindia_Scene_Preview \
    libCamera_ov8856ofilmfrontmipirawindia_TTPIC_Capture \
    libCamera_ov8856ofilmfrontmipirawindia_Video_1080 \
    libCamera_ov8856ofilmfrontmipirawindia_Video_720 \
    libCamera_ov8856ofilmfrontmipirawindia_Video_other \
    libCamera_ov8856ofilmfrontmipirawindia_Wechat_Call \
    libCamera_ov8856ofilmfrontmipirawindia_Wechat_Capture \
    libDR \
    libDefaultFpsActor \
    libFrameRecord \
    libJpgEncPipe \
    libNoFpsActor \
    libOpenCL \
    libSQLiteModule_VER_ALL \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libTEECommon \
    lib_bsscore \
    lib_sr_models \
    libaaa_ltm \
    libaaa_ltmx \
    libaal_cust \
    libaal_key \
    libaal_mtk \
    libaalservice \
    libaiawb_moon \
    libaiawb_moon_model \
    libaiawb_p1ggm \
    libaiawb_sun \
    libaiawb_sun_model \
    libalCFR \
    libappgamepq \
    libarcbokeh.preview \
    libarcsoft_beautyshot \
    libarcsoft_dualcam_refocus \
    libarcsoft_fbpre \
    libarcsoft_hdr_preview \
    libarcsoft_supernight \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbt-vendor \
    libc++_shared \
    libcam.afhal \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.ae \
    libcam.hal3a.v3.ai3a \
    libcam.hal3a.v3.awb \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.fsmgr \
    libcam.hal3a.v3.lscMgr \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.hal3a.v3.platform \
    libcam.hal3a.v3.resultpool \
    libcam.hal3a.v3 \
    libcam.halisp.buf \
    libcam.halisp.common \
    libcam.halisp \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.iopipe \
    libcam.isptuning \
    libcam.pdtblgen \
    libcam.seninfn3d \
    libcam.tuning.cache \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcamalgo.3dnr \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.ispfeature \
    libcamalgo.lmv \
    libcamalgo.lsc \
    libcamalgo.mfnr \
    libcamalgo.n3d \
    libcamalgo.nr \
    libcamalgo.platform \
    libcamalgo.platform2 \
    libcamalgo.rotate \
    libcamalgo.utility \
    libcamalgo.vpudsdn \
    libcamalgo.vsf \
    libcamalgo.warp \
    libcamdrv_imem \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera.custom.pd_buf_mgr \
    libcamera.customae \
    libcamera.customaf \
    libcamera.customawb \
    libcamera.customflk \
    libcamera_scene \
    libcameracustom.camera.3a \
    libcameracustom.camera.isp \
    libcameracustom.camera.sensors \
    libcameracustom.camera_exif \
    libcameracustom.eis \
    libcameracustom.flashlight \
    libcameracustom.lens \
    libcameracustom \
    libcares_naptr \
    libcarrierconfig \
    libccci_util \
    libcodec2_hidl@1.0-v31 \
    libcodec2_hidl@1.1-v31 \
    libcodec2_hidl@1.2-v31 \
    libcodec2_hidl_plugin-v31 \
    libcodec2_mtk_c2store \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcodec2_soft_common-v31 \
    libcodec2_vndk-v31 \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libcomposer_ext \
    libconnfem \
    libcustom_nvram \
    libdip_drv \
    libdip_imem \
    libdip_postproc \
    libdre \
    libeffecthal.base \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature.vsdof.hal \
    libfeature_3dnr \
    libfeature_eis \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libfingerprint.default \
    libforkexecwrap \
    libformatter \
    libgamehdr \
    libged \
    libgf_ca \
    libgf_hal \
    libgoodixhwfingerprint \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libhdrvideo \
    libheichal \
    libhfmanager \
    libhq_videofilter \
    libhwm \
    libifcutils_mtk \
    libimagebuffer_wrapper \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    libimgsensorca \
    libimsg_log \
    libispcameraca \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libksensor \
    liblpcnr \
    libm4u \
    libmfllcore \
    libmi_bokehpre \
    libmialgoengine \
    libmibokeh_mt6873 \
    libmipc \
    libmml \
    libmnetlink_v104 \
    libmnl \
    libmpbase \
    libmsnr \
    libmtk-fusion-ril-prop-vsim \
    libmtk-ril \
    libmtkares \
    libmtkcam.atmseventmgr \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_3rdparty.vidhance \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_owe \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-aov \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkcam_vsync_util \
    libmtkconfig \
    libmtkconfigutils \
    libmtkhardware_legacy \
    libmtkisp_metadata \
    libmtkmipc-ril \
    libmtknetcap \
    libmtknetutils \
    libmtkrilutils \
    libmtksysutils \
    libmtktinyxml \
    libmtkutils \
    liboemcrypto \
    libpq_cust_base \
    libpqframework \
    libpqparamparser \
    libratconfig \
    librilfusion \
    librpc \
    libsdk_sr \
    libsensor_custom \
    libsfplugin_ccodec_utils-v31 \
    libstereoinfoaccessor_vsdof \
    libstorage_otp \
    libsysenv \
    libteei_daemon_vfs \
    libthha \
    libtlcWidevineModularDrm \
    libtrm \
    libudf \
    liburee_meta_drmkeyinstall \
    libvia-ril \
    libviagpsrpc \
    libviamipc-ril \
    libvideofilter_only \
    libvidhance \
    libwifi-hal-mtk \
    libwpfa \
    libwvhidl \
    libxmi_high_dynamic_range \
    libwvdrmengine \
    libaiselector \
    libdpframework \
    libpq_prot \
    libmtkcam_streaminfo_plugin-p1stt \
    ov02b10_aac_macro_mipi_raw_IdxMgr \
    ov02b10_aac_macro_mipi_raw_tuning \
    ov48b_aac_main_mipi_raw_IdxMgr \
    ov48b_aac_main_mipi_raw_tuning \
    ov48b_qtech_main_mipi_raw_IdxMgr \
    ov48b_qtech_main_mipi_raw_india_tuning \
    ov48b_qtech_main_mipi_raw_tuning \
    ov8856_aac_front_mipi_raw_IdxMgr \
    ov8856_aac_front_mipi_raw_tuning \
    ov8856_ofilm_front_mipi_raw_IdxMgr \
    ov8856_ofilm_front_mipi_raw_india_tuning \
    ov8856_ofilm_front_mipi_raw_tuning \
    vendor.mediatek.hardware.bluetooth.audio@2.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.2 \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.camera.ccap@1.0 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.lbs@1.0 \
    vendor.mediatek.hardware.mmagent@1.0 \
    vendor.mediatek.hardware.mmagent@1.1 \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.mms@1.6 \
    vendor.mediatek.hardware.mtkradioex@2.0 \
    vendor.mediatek.hardware.mtkradioex@3.0 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    vendor.mediatek.hardware.power@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.10 \
    vendor.mediatek.hardware.pq@2.11 \
    vendor.mediatek.hardware.pq@2.12 \
    vendor.mediatek.hardware.pq@2.13 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    vendor.mediatek.hardware.pq@2.7 \
    vendor.mediatek.hardware.pq@2.8 \
    vendor.mediatek.hardware.pq@2.9 \
    vendor.mediatek.hardware.videotelephony@1.0 \
    HotwordEnrollmentOKGoogleRISCV \
    HotwordEnrollmentXGoogleRISCV \
    com.android.hotwordenrollment.common.util \
    gnss-mtk.xml \
    gnss@2.1-service.xml \
    lbs_hidl_service@1.0.xml \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    manifest_media_c2_V1_2_default.xml \
    bp_kmsetkey_ca \
    ccci_mdinit \
    ccci_rpcd \
    chipinfo \
    fuelgauged \
    fuelgauged_nvram \
    gsm0710muxd \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.gnss-service.mediatek \
    android.hardware.graphics.allocator@4.0-service-mediatek \
    android.hardware.keymaster@4.1-service.beanpod \
    android.hardware.media.c2@1.2-mediatek-64b \
    android.hardware.secure_element@1.2-service-mediatek \
    camerahalserver \
    mtkfusionrild \
    tetheroffloadservice \
    vendor.mediatek.hardware.mms@1.6-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.mediatek.hardware.pq@2.2-service \
    vtservice_hidl \
    lbs_hidl_service \
    lib3a.ccu.ddr \
    lib3a.ccu.dm \
    lib3a.ccu.pm \
    mi_thermald \
    mnld \
    mtk_agpsd \
    netdagent \
    nvram_daemon \
    teei_daemon \
    thermal \
    thermal_manager \
    thermalloadalgod \
    vpud \
    wlan_assistant \
    wmt_launcher \
    wmt_loader

PRODUCT_PACKAGES += \
    vendor_bin_hw_android_hardware_media_c2@1_2-mediatek \
    vendor_lib_libmtk_drvb_so \
    vendor_lib64_libaiselector_so \
    vendor_lib64_libdpframework_so \
    vendor_lib64_libmtk_drvb_so \
    vendor_lib64_libpq_prot_so
